name: CI

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:

jobs:
  verify:
    name: Maven Build
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: |
          mvn --version
          mvn --batch-mode --no-transfer-progress package
          echo "artifactName=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifactName }}
          path: |
            target/*.jar
            !target/original-*.jar
