name: CI

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:

jobs:
  verify:
    name: Build with Maven
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21, 22 ]

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Build with Maven
        run: |
          ./mvnw --version
          ./mvnw --batch-mode --no-transfer-progress package
          echo "artifact=$(./mvnw help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.java == 21
        with:
          name: ${{ env.artifact }}
          path: |
            target/*.jar
            !target/original-*.jar
